[oci_audit]
search = index=main sourcetype="oci:log" oracle.loggroupid=_audit

[oci_vcn_flow]
search = index=main sourcetype="oci:log" type=com.oraclecloud.vcn.flowlogs.DataEvent

[oci_objectstore]
search = index=main sourcetype="oci:log" type=com.oraclecloud.objectstorage*
